name: Test IIIF Collection Build
on: push
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: IIIF Presentation API 2.x Collection (Aggregation)
        run: npm run prebuild -- --path=./config/.fixtures/canopy.presentation-2.json
      - name: IIIF Presentation API 2.x Collection (Build)
        run: npm run test-build
      - name: IIIF Presentation API 3.0 Collection (Aggregation)
        run: npm run prebuild -- --path=./config/.fixtures/canopy.presentation-3.json
      - name: IIIF Presentation API 3.0 Collection (Build)
        run: npm run test-build
